config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#index"
  get 'static_pages/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def new
    end
    
    def index
    end
    
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navigation.html.erb
<div class="navigation">
        <ul>
            <li class="navigation text">login</li>
            <li class="navigation text"><%= link_to 'about', static_pages_about_path %></li>
            <li class="navigation text"><%= link_to 'front page', root_path %></li>
        </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SixOSevenApp</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!--font awesome for icons-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- google font loading-->
    <link href="https://fonts.googleapis.com/css?family=Oswald|Pacifico|Quicksand:300" rel="stylesheet">    
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="background-image"></div>
    
    <div class="content">
      <header>
      <%= render 'layouts/navigation' %>
    </header>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container-fluid">
    <div class="jumbotron jumbotron-fluid box margin-top">
       <h3 class="top-header subtitle">This app is proudly presented to you by Shiny Crab Studio (Formerly known as Wongkito Crabbing Company)</h3>
       <div class="row margin-top">
           <div class="col-md-4 center white-text">
               <%= image_tag("martin.png", class: "profile-pic img-thumbnail") %>
               <h4>Horseshoe Crab</h4>
               <p>Martin Loekito</p>
           </div>
           <div class="col-md-4 center white-text">
               <%= image_tag("jarold.png", class: "profile-pic img-thumbnail") %>
               <h4>Alaskan King Crab</h4>
               <p>Jarold Wong</p>
           </div>
           <div class="col-md-4 center white-text">
               <%= image_tag("jun.png", class: "profile-pic img-thumbnail") %>
               <h4>Hermit Crab</h4>
               <p>Jun Hwang</p>
           </div>
       </div>
    </div>
</div>

app/views/static_pages/index.html.erb
<div class="container-fluid margin-top">

    <p class="top-header logo">607</p>
    <p class="top-header subtitle">your one stop shop for all things 607.</p>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4 center">
            <div class="box">
                <i class="fa fa-calendar-check-o fa-5x"></i>
                    <br/>
                        <h3 class="option-text">
                            Check what's going on
                        </h3>
            </div>
        </div>
        <div class="col-md-4 center">
            <div class="box">
                <i class="fa fa-wrench fa-5x"></i>
                    <br/>
                        <h3 class="option-text">
                            Report maintenance issue
                        </h3>
            </div>
        </div>
        <div class="col-md-4 center">
            <div class="box">
            <i class="fa fa-list-alt fa-5x"></i>
                <br/>
                    <h3 class="option-text">
                        I'm in charge of lockup
                    </h3>
            </div>
        </div>
    </div>
    <!--<div class="row center spacer">-->
    <!--    <div class="col-md-4 header">-->
    <!--        <h3>Check what's going on</h3>-->
    <!--    </div>-->
    <!--    <div class="col-md-4 header">-->
    <!--        <h3>Report maintenance issue</h3>-->
    <!--    </div>-->
    <!--    <div class="col-md-4 header">-->
    <!--        <h3>I'm in charge of lockup</h3>-->
    <!--    </div>-->
    <!--</div>-->
</div>